[[assignments]]
name = "wc"
description = "something"
prefix = "wc-"

  [[assignments.tasks]]
  name = "test"
  queue = "test"
  image = "mocha"
  data = "/tmp/wc-tests"

  [[assignments.tasks]]
  name = "lint"
  queue = "lint"
  image = "steptw/eslint"
  data = "/github/somewhere_else"

[[assignments]]
name = "head"
description = "something"
prefix = "head-"

  [[assignments.tasks]]
  name = "test"
  queue = "test"
  image = "mocha"
  data = "/tmp/head_tests"

  [[assignments.tasks]]
    name = "lint"
    queue = "lint"
    image = "eslint"
    data = "/tmp/eslint"


[[assignments]]
name = "geometry"
description = "something"
prefix = "geometry-"

  [[assignments.tasks]]
  name = "test"
  queue = "test"
  image = "mocha"
  data = "/Users/ankoncha/Google Drive/test"

  [[assignments.tasks]]
    name = "lint"
    queue = "lint"
    image = "eslint"
    data = "/tmp/eslint"
